<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Avivits-MacBook-Pro.local" name="sanity.GrafanaWeb" tests="8" failures="1" timestamp="09 Aug 2021 15:34:30 GMT" time="48.010" errors="0">
  <testcase name="test02_verifyDefaultUsers" time="1.564" classname="sanity.GrafanaWeb">
    <failure type="java.lang.AssertionError" message="expected [99] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [99] but found [1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at extensions.Verifications.numberOfElements(Verifications.java:32)
at sanity.GrafanaWeb.test02_verifyDefaultUsers(GrafanaWeb.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- test02_verifyDefaultUsers -->
  <testcase name="test07_SearchUsers" time="14.053" classname="sanity.GrafanaWeb"/>
  <testcase name="test01_verifyHeader" time="6.127" classname="sanity.GrafanaWeb"/>
  <testcase name="test03_verifyNewUser" time="3.091" classname="sanity.GrafanaWeb"/>
  <testcase name="test04_verifyNewUserDeletion" time="3.687" classname="sanity.GrafanaWeb"/>
  <testcase name="test05_verifyProgressStep" time="0.479" classname="sanity.GrafanaWeb"/>
  <testcase name="test07_SearchUsers" time="4.181" classname="sanity.GrafanaWeb"/>
  <testcase name="test07_SearchUsers" time="14.828" classname="sanity.GrafanaWeb"/>
</testsuite> <!-- sanity.GrafanaWeb -->
